# Generated by Django 5.1.6 on 2025-03-17 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pie',
            name='desc',
            field=models.TextField(default='A really yummy pie, I really reccommend trying this one.'),
            preserve_default=False,
        ),
    ]
