# Generated by Django 5.1.6 on 2025-03-17 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0002_pie_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pie',
            name='desc',
            field=models.TextField(default='A really yummy pie. Highly Recoomended'),
        ),
    ]
