# Generated by Django 5.1.6 on 2025-03-18 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0003_alter_pie_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_app.pie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_app.user')),
            ],
            options={
                'unique_together': {('user', 'pie')},
            },
        ),
        migrations.AddField(
            model_name='pie',
            name='voters',
            field=models.ManyToManyField(related_name='voted_pies', through='exam_app.Vote', to='exam_app.user'),
        ),
    ]
